Fix drm_client_setup.h for Linux 6.14
In Linux 6.14 the public header file drm_client_setup.h
has been moved to include/drm/clients/ subdirectory.
See commit b86711c6d6e20e drm/client: Move public client header to clients/ subdirectory

This causes the following compile time error:

smi_drv.c:33:10: fatal error: drm/drm_client_setup.h: No such file or directory
   33 | #include <drm/drm_client_setup.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~

Adjust the code for kernels >= 6.14.

Signed-off-by: Massimiliano Pellizzer <massimiliano.pellizzer@canonical.com>