Remove driver date from struct drm_driver for Linux 6.14
In Linux 6.14 the field 'date' has been removed from the struct drm_driver.
See commit cb2e1c2136f716 drm: remove driver date from struct drm_driver and all drivers

This causes the following compile time error:

smi_drv.c:555:10: error: ‘struct drm_driver’ has no member named ‘date’
  555 |         .date = DRIVER_DATE,
      |          ^~~~

Adjusted the drm_driver structure initialization accordingly for kernels >= 6.14.

Signed-off-by: Massimiliano Pellizzer <massimiliano.pellizzer@canonical.com>